AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: "http://host.docker.internal:4571"
        S3_ENDPOINT: "http://localhost:4566"
        AWS_REGION: "us-east-1"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  CreateRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-recipe/
      Handler: app.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Recipes
      Events:
        CreateRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /recipes
            Method: post

  ListRecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list-recipes/
      Handler: app.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: Recipes
      Events:
        ListRecipes:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /recipes
            Method: get

  UpdateRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update-recipe/
      Handler: app.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Recipes
      Events:
        UpdateRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /recipes/{id}
            Method: put

  DeleteRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete-recipe/
      Handler: app.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Recipes
      Events:
        DeleteRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /recipes/{id}
            Method: delete

  GetRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-recipe/
      Handler: app.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: Recipes
      Events:
        GetRecipe:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /recipes/{id}
            Method: get

  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-presigned-url/
      Handler: app.handler
      Runtime: nodejs20.x
      Policies:
        - S3WritePolicy:
            BucketName: "summer-school-app"
      Environment:
        Variables:
          BUCKET: "summer-school-app"
      Events:
        GetPresignedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /uploads
            Method: post
