const IMAGE_BUCKET_NAME = "YOUR-IMAGE_BUCKET_NAME";
const IMAGE_BUCKET_REGION = "YOUR-REGION";
const API_URL = "YOUR-API-URL";

window.RUNTIME_CONFIG = {
  API_URL,
  IMAGE_BUCKET_URL: `https://${IMAGE_BUCKET_REGION}.s3.${IMAGE_BUCKET_REGION}.amazonaws.com`,
};
