const IMAGE_BUCKET_NAME = "YOUR-IMAGE_BUCKET_NAME";
const IMAGE_BUCKET_REGION = "YOUR-REGION";
const API_URL = "YOUR-API-URL";
const AUTHORITY = "YOUR-COGNITO-AUTHORITY";
const CLIENT_ID = "YOUR-COGNITO-CLIENT-ID";
const REDIRECT_URI = "YOUR-FRONTEND-REDIRECT_URI";
const USER_POOL_DOMAIN = "YOUR-COGNITO-USER-POOL-DOMAIN";
const SIGN_OUT_URL = "YOUR-FRONTEND-SIGN-OUT-URL";

window.RUNTIME_CONFIG = {
  API_URL,
  IMAGE_BUCKET_URL: `https://${IMAGE_BUCKET_NAME}.s3.${IMAGE_BUCKET_REGION}.amazonaws.com`,
  AUTHORITY,
  CLIENT_ID,
  REDIRECT_URI,
  USER_POOL_DOMAIN,
  SIGN_OUT_URL,
};
